# Copyright (C)2014-2025 Gowin Semiconductor Corporation.
# All rights reserved.
# File Title: Timing Constraints file for Tang Nano 9K HDMI Encoder (Video Only)
# Part Number: GW1NR-LV9QN88C6/I5
# Device: GW1NR-9C
# Project: Tang Nano 9K HDMI Video
# Updated: 2025-10-13

# ===== PRIMARY CLOCKS =====
# Define primary clock - 27 MHz crystal input
# Period = 1/27MHz = 37.037 ns
create_clock -name clk_crystal -period 37.037 -waveform {0 18.518} [get_ports {clk_27m}]

# ===== GENERATED CLOCKS =====
# Gowin automatically infers clocks from rPLL and CLKDIV primitives.
# Manual generated clock definitions are not needed and can cause constraint errors
# if hierarchical paths don't match the synthesized netlist.
#
# Auto-inferred clocks from design:
#   - 126 MHz serial clock: 27 MHz × (FBDIV+1)/(IDIV+1) = 27 × 14/3 = 126 MHz
#   - 25.2 MHz pixel clock: 126 MHz ÷ 5 = 25.2 MHz
#
# The Gowin timing analyzer will automatically propagate these clocks through
# the design and analyze setup/hold timing on all synchronous paths.

# ===== ASYNCHRONOUS INPUTS =====
# Set a false path for the asynchronous reset button input.
# This is safe because the signal is passed through a synchronizer
# (rst_sync_n) before being used in any synchronous domain.
set_false_path -from [get_ports {rst_n}]

# ===== HDMI OUTPUT CONSTRAINTS =====
# The TMDS outputs are generated by OSER10 primitives (10:1 serializers) driven
# by both the pixel clock (PCLK) and serial clock (FCLK). The serializers handle
# internal timing and bit alignment.
#
# HDMI uses source-synchronous signaling where the clock is transmitted alongside
# the data. The receiving device uses the forwarded clock to sample the data, so
# board-level setup/hold timing is not constrained by the FPGA's clock.
#
# Setting false paths allows the Gowin tools to optimize internal logic without
# being constrained by output timing that is actually determined by the TMDS
# protocol and receiving device.
set_false_path -to [get_ports {tmds_data_p[*]}]
set_false_path -to [get_ports {tmds_data_n[*]}]
set_false_path -to [get_ports {tmds_clk_p}]
set_false_path -to [get_ports {tmds_clk_n}]

# ===== CLOCK DOMAIN RELATIONSHIPS =====
# The pixel clock (25.2 MHz) and serial clock (126 MHz) are synchronous - both
# derived from the same rPLL with a 5:1 frequency relationship. Timing paths
# between these domains are automatically analyzed by the Gowin timing engine.